[config]

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-template.toml'
output_path = '~/.config/starship.toml'

[templates.niri]
input_path = '~/.config/matugen/templates/niri.kdl.template'
output_path = '~/.config/niri/config.kdl'
