[general]
output_path = "~/.config/niri/config.kdl"

[genconfig]
watch_dir = "~/.config/niri/configs/"
sources = [
    "~/.config/niri/configs/input.kdl",
    "~/.config/niri/configs/output.kdl",
    "~/.config/niri/configs/visuals.kdl",
    "~/.config/niri/configs/variables.kdl",
    "~/.config/niri/configs/startup.kdl",
    "~/.config/niri/configs/keybinds.kdl",
]

[workspaces]
dmenu_command = "rofi -demenu"
task_delay = 0.8

[workspaces.items]
