[font]
size = 11.0
bold = { family = "Fira Code Nerd Font", style = "Bold" }
bold_italic = { family = "Fira Code Nerd Font", style = "Bold Italic" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

# [font.italic]
# family = "Fira Code Nerd Font Regular"
# style = "Italic"
