[keyboard]
bindings = [
    {key = "Plus", mods = "Control", action = "IncreaseFontSize"},
    {key = "Minus", mods = "Control", action = "DecreaseFontSize"},
    {key = "Return", mods = "Control|Shift", action = "SpawnNewInstance"},
]
